### ISSUE TITLE
Unable to exit script gracefully while a navigation is in progress

### ISSUE THREAD

**Issue by mikeyy** [miyakogi/pyppeteer#121] opened 2018-08-03 16:02 UTC
It appears the culprit is in the connection module, `Connection()._recv_loop()`

I've simply added an `await asyncio.sleep(0)` at the end of the while loop. So far the issue hasn't reappeared.

**Comment by miyakogi** [comment] 2018-08-06 02:41
Does this issue still reproduce on dev branch on github?
Please try `pip install git+git://github.com/miyakogi/pyppeteer@dev`.

**Comment by mikeyy** [comment] 2018-08-07 04:33
Sorry for the delay, trying to get things working smoothly while multithreading on one of my projects that's built with Pyppeteer. After installing the dev branch in my environment and spawning a couple of browsers that all terminated without a hitch, this issue looks resolved! I'll report back if any other problems arise. Do you happen to have an expected date for the next version release?

If you find the time, would you mind inspecting my multithreaded attempt or my project in general that depends on your library? 

Thanks

**Comment by miyakogi** [comment] 2018-08-11 04:18
Thank you for information.
I close this issure since v0.0.20 is released.

**Closed by miyakogi** 2018-08-11 04:18 UTC
