### ISSUE TITLE
"node.click()" or "node.tap()" doesn't work for "a" html tag that has long text and auto-wrap

### ISSUE THREAD

**Issue by csugzq** [miyakogi/pyppeteer#111] opened 2018-07-19 07:30 UTC
It's weird when I try to click a "a" tag that has long text from page and it doesn't work. But for a short "a" tag, it does work. Have anyone ever been in this situation?

**Comment by miyakogi** [comment] 2018-08-06 04:53
Sorry for late response.
I reproduced this issue.
It seems to be a bug.

Workaround is:

```python
element = await page.querySelector('a')  # or any proper selector
await page.evaluate('(element) => element.click()', element)
```

**Comment by miyakogi** [comment] 2018-08-06 05:37
This is a bug of puppeteer fixed in puppeteer v1.6.0, but pyppeteer does not catch up yet, sorry.

**Comment by csugzq** [comment] 2018-08-16 05:48
@miyakogi Thanks

**Comment by miyakogi** [comment] 2018-09-12 07:31
Pyppeteer 0.0.24 caught up puppeteer v1.6.0 and now fixed this issue.

**Closed by miyakogi** 2018-09-12 07:31 UTC
Labels: bug
